### ISSUE TITLE
Please add a license file, read me and a screen shot

### ISSUE THREAD

**Issue by unixorn** [onthedock/xavi.zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I only add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Finally, don't take these as criticisms of the work you've done, they're meant to make a more useful entry in the plugin/theme list.

Thanks!

**Comment by onthedock** [comment]
Hi @unixorn:

Please, review the current status of the repo/theme to see if the changes made fix the issue:

- d14bd7b16b968c36a6d0e8b7a3f6001ad7f8d0c7 Adds LICENSE
- 796ed24e47e12e4fd2ac01c71e7a9434ed68b2e3 Adds README.md
- fdacff40d75bd9066757a466b11a29e8378614ca Adds screenshot

I shared the motivation behind the creation of *yet another theme* and the alterations made to the original **gnzh** on the blog entry [Tema personalizado de Oh My Zsh](https://onthedock.github.io/post/211229-tema-personalizado-de-oh-my-zsh/) (in spanish).

Happy New Year!

Best regards,

Xavi
